// Temporary stub generated by template. Run `pnpm --filter @template/convex convex codegen`
// to replace with real generated code.

export const query = (def) => def;
export const mutation = (def) => def;
export const action = (def) => def;