// Temporary stub generated by template. Run `pnpm --filter @template/backend convex codegen`
// to replace with real generated code.

export type QueryCtx = { db: any };
export type MutationCtx = { db: any };
export type ActionCtx = unknown;

export declare const query: <T extends { args: any; handler: any }>(def: T) => T;
export declare const mutation: <T extends { args: any; handler: any }>(def: T) => T;
export declare const action: <T extends { args: any; handler: any }>(def: T) => T;
