// Temporary stub generated by template. Run `pnpm --filter @template/convex convex codegen`
// to replace with real generated code.

export type QueryCtx = { db: any };
export type MutationCtx = { db: any };
export type ActionCtx = unknown;